### ISSUE TITLE
http2 error: protocol error: refused stream before processing any application logic

### ISSUE THREAD

**Issue by ChoppyThing** [postcss/postcss-deno#2]
Hello,
I hope i'm not missing something on my development machine.
I'm trying to port some old code to deno and i'm getting this error when running the example : 

Download https://dev.jspm.io/npm:nanoid@3.1.16/non-secure/index.dew.js
error: error sending request for url (https://dev.jspm.io/npm:caniuse-lite@1.0.30001158/data/features/nav-timing.dew.js): http2 error: protocol error: refused stream before processing any application logic
    at https://dev.jspm.io/npm:caniuse-lite@1?dew:376:0

Is it me missing something here ?

**Comment by oscarotero** [comment]
This is a problem with the package caniuse-lite returned by jspm.io, a dependency of autoprefixer. Sadly, autoprefixer is not ported (yet) to deno, so it has to be loaded from jspm.io, which fails sometimes.

**Comment by ChoppyThing** [comment]
Thanks for the answer !
If i understand, i can't use this for now ? Or is there a way to retrieve autoprefixer?
I tried this like 10 times for the two past weeks, and the packages are never fully resolved

**Comment by oscarotero** [comment]
It's weird because I'm using it and never had this error (at least until now).
The only difference is that I'm using it from postcssPresentEnv (loaded from jspm too):
https://github.com/lumeland/lume/blob/master/deps/postcss.js

Maybe it works with a different version (I had errors with some versions of some packages in jspm.io, so try to find a version that works fine).

**Comment by ChoppyThing** [comment]
Thanks for your answer !

**Comment by ldexterldesign** [comment]
👋 https://github.com/jspm/project/issues/95
